using System.Configuration;
using System.Web.Configuration;
using System.Web.Hosting;

namespace Uniframework.Services.db4oProviders
{
    public interface IValidationKeyInfo
    {
        string GetKey();
        bool IsAutoGenerated();
    }

    public sealed class ValidationKeyInfo : IValidationKeyInfo
    {
        private readonly string sectionName;

        public ValidationKeyInfo(string sectionName)
        {
            this.sectionName = sectionName;
        }

        #region IValidationKeyInfo Members

        public string GetKey()
        {
            Configuration cfg = WebConfigurationManager.OpenWebConfiguration(HostingEnvironment.ApplicationVirtualPath);
            return ((MachineKeySection)cfg.GetSection(sectionName)).ValidationKey;
        }

        public bool IsAutoGenerated()
        {
            return GetKey().Contains("AutoGenerate");
        }

        #endregion
    }
}