using System.Configuration;
using System.Web.Configuration;

namespace Uniframework.Services.db4oProviders
{
    public interface IValidationKeyInfo
    {
        string GetKey();
        bool IsAutoGenerated();
    }

    public sealed class ValidationKeyInfo : IValidationKeyInfo
    {
        public ValidationKeyInfo(string sectionName)
        {
            this.sectionName = sectionName;
        }

        public string GetKey()
        {
            Configuration cfg = WebConfigurationManager.OpenWebConfiguration(System.Web.Hosting.HostingEnvironment.ApplicationVirtualPath);
            return ((MachineKeySection)cfg.GetSection(this.sectionName)).ValidationKey;
        }

        public bool IsAutoGenerated()
        {
            return this.GetKey().Contains("AutoGenerate");
        }

        private readonly string sectionName;
    }
}